import GameEvent from "./game-events.js";
var Input;
(function (Input) {
    let KeyCode;
    (function (KeyCode) {
        KeyCode["KeyA"] = "KeyA";
        KeyCode["KeyB"] = "KeyB";
        KeyCode["KeyC"] = "KeyC";
        KeyCode["KeyD"] = "KeyD";
        KeyCode["KeyE"] = "KeyE";
        KeyCode["KeyF"] = "KeyF";
        KeyCode["KeyG"] = "KeyG";
        KeyCode["KeyH"] = "KeyH";
        KeyCode["KeyI"] = "KeyI";
        KeyCode["KeyJ"] = "KeyJ";
        KeyCode["KeyK"] = "KeyK";
        KeyCode["KeyL"] = "KeyL";
        KeyCode["KeyM"] = "KeyM";
        KeyCode["KeyN"] = "KeyN";
        KeyCode["KeyO"] = "KeyO";
        KeyCode["KeyP"] = "KeyP";
        KeyCode["KeyQ"] = "KeyQ";
        KeyCode["KeyR"] = "KeyR";
        KeyCode["KeyS"] = "KeyS";
        KeyCode["KeyT"] = "KeyT";
        KeyCode["KeyU"] = "KeyU";
        KeyCode["KeyV"] = "KeyV";
        KeyCode["KeyW"] = "KeyW";
        KeyCode["KeyX"] = "KeyX";
        KeyCode["KeyY"] = "KeyY";
        KeyCode["KeyZ"] = "KeyZ";
        KeyCode["Digit0"] = "Digit0";
        KeyCode["Digit1"] = "Digit1";
        KeyCode["Digit2"] = "Digit2";
        KeyCode["Digit3"] = "Digit3";
        KeyCode["Digit4"] = "Digit4";
        KeyCode["Digit5"] = "Digit5";
        KeyCode["Digit6"] = "Digit6";
        KeyCode["Digit7"] = "Digit7";
        KeyCode["Digit8"] = "Digit8";
        KeyCode["Digit9"] = "Digit9";
        KeyCode["Numpad0"] = "Numpad0";
        KeyCode["Numpad1"] = "Numpad1";
        KeyCode["Numpad2"] = "Numpad2";
        KeyCode["Numpad3"] = "Numpad3";
        KeyCode["Numpad4"] = "Numpad4";
        KeyCode["Numpad5"] = "Numpad5";
        KeyCode["Numpad6"] = "Numpad6";
        KeyCode["Numpad7"] = "Numpad7";
        KeyCode["Numpad8"] = "Numpad8";
        KeyCode["Numpad9"] = "Numpad9";
        KeyCode["F1"] = "F1";
        KeyCode["F2"] = "F2";
        KeyCode["F3"] = "F3";
        KeyCode["F4"] = "F4";
        KeyCode["F5"] = "F5";
        KeyCode["F6"] = "F6";
        KeyCode["F7"] = "F7";
        KeyCode["F8"] = "F8";
        KeyCode["F9"] = "F9";
        KeyCode["F10"] = "F10";
        KeyCode["F11"] = "F11";
        KeyCode["F12"] = "F12";
        KeyCode["Backquote"] = "Backquote";
        KeyCode["Tab"] = "Tab";
        KeyCode["CapsLock"] = "CapsLock";
        KeyCode["ShiftLeft"] = "ShiftLeft";
        KeyCode["ShiftRight"] = "ShiftRight";
        KeyCode["ControlLeft"] = "ControlLeft";
        KeyCode["MetaLeft"] = "MetaLeft";
        KeyCode["AltLeft"] = "AltLeft";
        KeyCode["Space"] = "Space";
        KeyCode["AltRight"] = "AltRight";
        KeyCode["ControlRight"] = "ControlRight";
        KeyCode["Enter"] = "Enter";
        KeyCode["Backslash"] = "Backslash";
        KeyCode["Backspace"] = "Backspace";
        KeyCode["Equal"] = "Equal";
        KeyCode["Minus"] = "Minus";
        KeyCode["BracketLeft"] = "BracketLeft";
        KeyCode["BracketRight"] = "BracketRight";
        KeyCode["Semicolon"] = "Semicolon";
        KeyCode["Quote"] = "Quote";
        KeyCode["Comma"] = "Comma";
        KeyCode["Period"] = "Period";
        KeyCode["Slash"] = "Slash";
        KeyCode["ArrowUp"] = "ArrowUp";
        KeyCode["ArrowDown"] = "ArrowDown";
        KeyCode["ArrowLeft"] = "ArrowLeft";
        KeyCode["ArrowRight"] = "ArrowRight";
    })(KeyCode = Input.KeyCode || (Input.KeyCode = {}));
    class AnyKeyboardEvent extends GameEvent {
    }
    class AnyMouseEvent extends GameEvent {
    }
    Input.KeyPressed = new AnyKeyboardEvent();
    Input.KeyDown = new AnyKeyboardEvent();
    Input.KeyUp = new AnyKeyboardEvent();
    Input.MouseClick = new AnyMouseEvent();
})(Input || (Input = {}));
export default Input;
